name: Release Sector Package
on:
  push:
    tags:
      - '*'
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Zip Package
      uses: thedoctor0/zip-release@0.6.2
      with:
        type: 'zip'
        filename: 'Hong-Kong-Sector-Package.zip'
        exclusions: '*.git* Legacy* Data/Settings/Legacy* Data/ASR/Legacy*'
    - name: Zip Legacy Package
      uses: thedoctor0/zip-release@0.6.2
      with:
        type: 'zip'
        filename: 'Hong-Kong-Sector-Package-Legacy.zip'
        exclusions: '*.git* *.vbs *TOPSKY.prf Data/Plugins/TopSky Data/Plugins/HKvACC* Data/Plugins/InitialClimbPlugin Data/Plugins/Ground* Data/Plugins/vSMR*'
    - name: Upload Packages
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "Hong-Kong-Sector-Package.zip, Hong-Kong-Sector-Package-Legacy.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
